/**
 * Canvas data layer — filesystem-backed.
 *
 * Each node = directory at projects/<project>/canvas/nodes/<id>/ with:
 *   plan.md          — master-for-subtree, child-to-parent
 *   meta.json        — kind, state, parent, deps, timestamps, confidence, classification, badge
 *   discussions/     — jsonl threads per topic
 *   outputs/         — artifacts
 *
 * graph.json at canvas/ root indexes edges + adjacency.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "~/config";
import { projectMeta } from "~/project/scaffold";

// 6-altitude architecture (see docs/PROJECT_SHAPE.md):
//
//   Project  ─ Layer (infra | middle | application)               altitude 1
//   Plane    ─ frontend | backend | data | integration | x-cut    altitude 2
//   Surface  ─ named region with manifest_globs                   altitude 3
//   Story    ─ forward-looking feature/ask/capability            ┐
//   Epic     ─ backward-looking bug/regression/refactor          ┘ altitude 4
//   Task     ─ one concrete executable unit                       altitude 5
//   Subtask  ─ atomic step inside a Task when needed              altitude 6
//
// Theme/Track/Module are pre-altitude vocabulary kept so existing legacy
// canvases load. New nodes proposed by Drafter must use Plane/Surface/Story/Epic.
export type NodeKind =
  | "Project"
  | "Plane"      // altitude 2 — engineering plane: frontend/backend/data/integration/cross-cutting
  | "Surface"    // altitude 3 — named region with file-pattern manifest the Implementer is allowed to write to
  | "Story"      // altitude 4 forward — feature/ask/capability ("As a X, I want Y")
  | "Epic"       // altitude 4 backward — regression/bug/refactor that fixes shipped work
  | "Task"
  | "Subtask"
  | "Decision"
  | "Research"
  | "Risk"
  | "Artifact"
  | "Milestone"
  | "Consultation" // Pillar B (Session 4) — meta-tracking node for off-platform expert
                   // conversations (lawyer, accountant, designer, govt desk, …). Atelier
                   // does NOT host the chat; it persists the question + answer so the
                   // brain can ripple the answer into dependent work. Founder creates
                   // these manually; Fixer surrender suggests them.
  | "Theme"      // @deprecated pre-altitude — outcome-grouped chunk; new work uses Surface or Story
  | "Track"      // @deprecated pre-altitude — alias for Theme
  | "Module";    // @deprecated pre-altitude — alias for Story

// Canvas reframe (2026-05-04, see docs/CANVAS_REFRAME_DECISIONS.md):
//   - `triage` is the parking column for rough ideas; inline `+` lands here.
//   - `archived` replaces `abandoned` for new emissions; `abandoned` kept as
//     a legacy alias so existing meta.json rows still load. UI buckets both
//     into the Archive column.
export type NodeState = "triage" | "proposed" | "approved" | "in-progress" | "review" | "done" | "blocked" | "archived" | "abandoned";

export type NodeBadge = "auto" | "proposed" | "in-progress" | "blocked" | "review" | "done" | "drift";

export type ProposedBy = "drafter" | "founder" | "reflection-worker" | "system" | "scaffold";

/** Founder-facing priority. Distinct from confidence (certainty of fit). */
export type Priority = "P0-now" | "P1-soon" | "P2-later" | "P3-backlog";

export interface NodeMeta {
  id: string;
  kind: NodeKind;
  intent: string;
  // 2-word glanceable label. Required. Generated by the proposing agent at
  // propose time so the UI never has to derive one from the full intent blob.
  title: string;
  state: NodeState;
  badge: NodeBadge;
  parent_id: string | null;
  dependencies: string[];
  confidence: "high" | "medium" | "low";
  proposed_by: ProposedBy;
  /** Founder-facing priority. Defaults to P2-later if not set. */
  priority?: Priority;
  /** Cycle tag (e.g. "c1", "c2", "c1-discovery", "c2-inbox"). Null = backlog. */
  cycle?: string | null;
  /** On Project-kind only: one-line outcome statement ("first real user completes audit flow"). */
  outcome?: string | null;
  /** On Project-kind only: which Layer the project sits at (altitude 1). Set once during onboarding. */
  layer?: "infra" | "middle" | "application" | null;
  /** On Plane-kind only: which engineering plane (altitude 2). */
  plane_kind?: "frontend" | "backend" | "data" | "integration" | "cross-cutting" | null;
  /** On Plane/Surface-kind only: ID of the parent Plane node (Plane has no parent_plane). Distinct from parent_id which is the canvas tree parent. */
  parent_plane_id?: string | null;
  /** On Surface-kind only: glob patterns this Surface owns. Implementer writes are gated to this set. */
  manifest_globs?: string[];
  /** On Surface-kind only: free-form tag the founder uses ("now", "canvas", "agents", "brain", "settings", "world", …). */
  surface_kind?: string | null;
  /** On Surface-kind only: lifecycle. Drafter cannot emit Tasks against deprecated Surfaces. */
  surface_status?: "proposed" | "active" | "deprecated" | null;
  /** On Story/Epic-kind only: IDs of Surface nodes this ask touches. Inherited by descendant Tasks. */
  touches?: string[];
  /** On Task/Subtask-kind only: opaque cycle-task identifier ("s-1-t-7") for queue ordering and supersession audit. */
  lock_id?: string | null;
  /** On Task/Subtask-kind only: 0.0–1.0 Drafter-computed urgency. Founder never sets this directly. */
  priority_score?: number | null;
  /** On Task/Subtask-kind only: ID of the Task this one supersedes. The pivot mechanism. */
  supersedes?: string | null;
  /** On Milestone-kind only: ISO-8601 date (YYYY-MM-DD) when the milestone is targeted to ship. */
  target_date?: string | null;
  /**
   * Cofounder collaboration. When `mark_for_discussion=true`, the assigned
   * user's next Drafter session boot-prompt surfaces this card with the
   * agenda as the conversation seed. Drafter captures the resolution as a
   * comment on the card and clears the flag. See docs/CANVAS_REFRAME_DECISIONS.md.
   */
  mark_for_discussion?: boolean;
  discussion_agenda?: string | null;
  assigned_to_user_id?: string | null;
  /**
   * Consultation kind only (Session 4 — Pillar B, off-platform expert tracking).
   * Atelier is the persistence layer; the actual conversation happens off-platform
   * (email/Slack/Calendly/phone). When `answer` transitions null → non-null, the
   * route writes a brain artifact at og_artifacts/brain/projects/<P>/consultations/<id>.md
   * so dependent work picks up the new context at next session boot.
   */
  expert_role?: string | null;       // "legal counsel" / "tax accountant" / …
  channel?: string | null;           // "email" / "slack" / "calendly" / "phone" / "in-person"
  question?: string | null;          // the ask itself
  answer?: string | null;            // filled when off-platform conversation completes
  deadline?: string | null;          // ISO date (YYYY-MM-DD)
  answered_at?: string | null;       // set by route when `answer` first becomes non-null
  /**
   * True when this node was auto-seeded by the project scaffold as a slot
   * for Drafter to fill. Drafter's "fill, don't create" rule (per
   * agents/principles/drafter.md) says: when a placeholder exists at the
   * target altitude, RENAME or REPLACE it rather than adding alongside.
   * Once Drafter renames, set placeholder=false to commit the slot.
   */
  placeholder?: boolean;
  classification?: {
    breaking: "safe" | "caution" | "breaking";
    blast_radius: "low" | "medium" | "high";
    domain_sensitivity: "none" | "soft" | "hard";
    vision_alignment: "high" | "medium" | "low";
    novelty: "routine" | "incremental" | "novel";
  };
  created_at: string;
  updated_at: string;
}

export type EdgeKind = "depends-on" | "produces" | "changes" | "discussed-in" | "blocks" | "parent-child" | "ships-in";

export interface Edge {
  from: string;
  to: string;
  kind: EdgeKind;
}

interface Graph {
  edges: Edge[];
}

function canvasRoot(project: string): string {
  return resolve(config.projectsDir, project, "canvas");
}
function nodesRoot(project: string): string {
  return resolve(canvasRoot(project), "nodes");
}
function nodeDir(project: string, id: string): string {
  return resolve(nodesRoot(project), id);
}
function graphPath(project: string): string {
  return resolve(canvasRoot(project), "graph.json");
}

export function ensureCanvas(project: string): void {
  mkdirSync(nodesRoot(project), { recursive: true });
  if (!existsSync(graphPath(project))) {
    writeFileSync(graphPath(project), JSON.stringify({ edges: [] }, null, 2));
  }
}

function readGraph(project: string): Graph {
  ensureCanvas(project);
  return JSON.parse(readFileSync(graphPath(project), "utf-8"));
}
function writeGraph(project: string, g: Graph): void {
  writeFileSync(graphPath(project), JSON.stringify(g, null, 2));
}

function genId(): string {
  return `n_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
}

export interface ProposeNodeInput {
  project: string;
  kind: NodeKind;
  intent: string;
  // 2 words max, describes the node at a glance. Proposing agent generates it.
  title: string;
  parent_id?: string | null;
  dependencies?: string[];
  confidence: "high" | "medium" | "low";
  proposed_by?: ProposedBy;
  priority?: Priority;
  cycle?: string | null;
  outcome?: string | null;      // Project kind only
  target_date?: string | null;  // Milestone kind only
  classification?: NodeMeta["classification"];
  // 6-altitude metadata (see docs/PROJECT_SHAPE.md). Omitted on legacy kinds.
  layer?: NodeMeta["layer"];
  plane_kind?: NodeMeta["plane_kind"];
  parent_plane_id?: string | null;
  manifest_globs?: string[];
  surface_kind?: string | null;
  surface_status?: NodeMeta["surface_status"];
  touches?: string[];
  lock_id?: string | null;
  priority_score?: number | null;
  supersedes?: string | null;
  /** Auto-seeded slot — see NodeMeta.placeholder. */
  placeholder?: boolean;
}

// Token-overlap Jaccard — cheap dup detection, no embeddings.
function tokenize(s: string): string[] {
  return s.toLowerCase().replace(/[^a-z0-9 ]+/g, " ").split(/\s+/).filter(t => t.length > 2);
}
function jaccard(a: string[], b: string[]): number {
  const sa = new Set(a), sb = new Set(b);
  let inter = 0;
  for (const t of sa) if (sb.has(t)) inter++;
  const union = sa.size + sb.size - inter;
  return union === 0 ? 0 : inter / union;
}

const SIBLING_INTENT_SIM_THRESHOLD = 0.6;
const PRE_MVP_MAX_SIBLINGS = 8;

function siblingsOf(project: string, parentId: string | null): NodeMeta[] {
  return listNodes(project).filter(n => (n.parent_id ?? null) === (parentId ?? null));
}
function hasSimilarSibling(siblings: NodeMeta[], intent: string): boolean {
  const incoming = tokenize(intent);
  if (incoming.length === 0) return false;
  return siblings.some(s => jaccard(tokenize(s.intent), incoming) >= SIBLING_INTENT_SIM_THRESHOLD);
}

// 6-altitude convergence rules (see docs/PROJECT_SHAPE.md "Convergence rules"):
//   • Plane requires Project parent (via parent_id) and the project must have a `layer`.
//   • Surface requires a Plane parent_plane_id; the referenced node must exist + be `kind: Plane`.
//   • Story/Epic require non-empty touches, and every touched id must resolve to an existing Surface
//     whose status is not "deprecated".
//   • Task/Subtask inherit touches from their parent Story/Epic (or carry their own; same gate applies).
//
// proposeNode raises on hard violations (no Plane parent for a Surface) and silently demotes soft
// violations to state: "proposed" so Drafter has visible feedback to fix at draft time without
// burning the canvas.
function validateAltitudeOrThrow(input: ProposeNodeInput, allNodes: NodeMeta[]): void {
  if (input.kind === "Plane") {
    if (!input.parent_id) {
      throw new Error("Plane node requires parent_id pointing at the Project node");
    }
    const project = allNodes.find((n) => n.id === input.parent_id);
    if (!project || project.kind !== "Project") {
      throw new Error(`Plane.parent_id must reference a Project (got ${project?.kind ?? "missing"})`);
    }
    if (!project.layer) {
      throw new Error("Project must have a `layer` set (infra | middle | application) before Planes can be proposed");
    }
    if (!input.plane_kind) {
      throw new Error("Plane node requires plane_kind (frontend | backend | data | integration | cross-cutting)");
    }
  }
  if (input.kind === "Surface") {
    if (!input.parent_plane_id) {
      throw new Error("Surface node requires parent_plane_id pointing at a Plane node");
    }
    const plane = allNodes.find((n) => n.id === input.parent_plane_id);
    if (!plane || plane.kind !== "Plane") {
      throw new Error(`Surface.parent_plane_id must reference a Plane (got ${plane?.kind ?? "missing"})`);
    }
  }
  if (input.kind === "Story" || input.kind === "Epic") {
    // Hard gate: Story/Epic MUST declare which Surface(s) they hit. Previously
    // soft-gated (empty allowed at "proposed") but that just deferred the
    // failure to the approve transition where Drafter no longer had context
    // about why it broke. Erroring at propose-time gives Drafter immediate,
    // actionable feedback. The principles already require this — see
    // drafter.md → "Node emission discipline / required fields".
    const touches = input.touches ?? [];
    if (touches.length === 0) {
      throw new Error(
        `${input.kind} node "${input.title}" requires non-empty 'touches' (Surface IDs). ` +
        `Pick from existing Surfaces shown in the project-context block, or propose a new Surface first.`
      );
    }
    validateTouches(touches, allNodes);
  }
  if (input.kind === "Task" || input.kind === "Subtask") {
    // Task/Subtask: either declare own `touches`, OR have a parent_id pointing
    // at a Story/Epic that already declares them. Inheritance preserved.
    // If neither path resolves to a valid Surface, fail loudly at propose
    // time rather than silently producing an un-runnable node.
    const ownTouches = input.touches ?? [];
    if (ownTouches.length > 0) {
      validateTouches(ownTouches, allNodes);
      return;
    }
    if (!input.parent_id) {
      throw new Error(
        `${input.kind} node "${input.title}" requires either non-empty 'touches' or a 'parent_id' ` +
        `pointing at a Story/Epic that declares touches.`
      );
    }
    const parent = allNodes.find((n) => n.id === input.parent_id);
    if (!parent) {
      throw new Error(
        `${input.kind}.parent_id ${input.parent_id} does not resolve to any node. ` +
        `Either set 'touches' directly or fix the parent_id.`
      );
    }
    const inheritedTouches = parent.touches ?? [];
    if (inheritedTouches.length === 0) {
      throw new Error(
        `${input.kind} node "${input.title}" inherits empty 'touches' from parent ` +
        `${parent.kind} ${parent.id}. Either set touches on this node directly or fix the parent's touches.`
      );
    }
    // Inherited touches were already validated when the parent was proposed,
    // but a Surface could have been retired since — re-validate so a stale
    // parent doesn't let a deprecated Surface slip through.
    validateTouches(inheritedTouches, allNodes);
  }
}

function validateTouches(touches: string[], allNodes: NodeMeta[]): void {
  for (const sid of touches) {
    const surface = allNodes.find((n) => n.id === sid);
    if (!surface || surface.kind !== "Surface") {
      throw new Error(`touches: id ${sid} does not resolve to a Surface (got ${surface?.kind ?? "missing"})`);
    }
    if (surface.surface_status === "deprecated") {
      throw new Error(`touches: Surface ${sid} ("${surface.title}") is deprecated and cannot be touched by new work`);
    }
  }
}

export function proposeNode(input: ProposeNodeInput): NodeMeta {
  ensureCanvas(input.project);
  const allNodes = listNodes(input.project);
  validateAltitudeOrThrow(input, allNodes);
  const id = genId();
  const now = new Date().toISOString();

  const stage = projectMeta(input.project)?.stage ?? "pre-mvp";
  const siblings = siblingsOf(input.project, input.parent_id ?? null);
  const duplicateLikely = hasSimilarSibling(siblings, input.intent);
  const crowded = siblings.length >= PRE_MVP_MAX_SIBLINGS;

  let autoEligible = false;
  if (stage === "experimental-sandbox") {
    autoEligible = input.confidence === "high";
  } else if (stage === "onboarding" || stage === "pre-mvp") {
    // Classifier off, but still gate on dup + crowding so the proposing
    // agent can't flood the Canvas unseen — true even during onboarding
    // where Onboarder may be shaping rapidly.
    autoEligible = input.confidence === "high" && !duplicateLikely && !crowded;
  } else {
    // post-mvp — full 5D classification required, all slots clean.
    autoEligible =
      input.confidence === "high" &&
      !!input.classification &&
      input.classification.breaking === "safe" &&
      input.classification.blast_radius === "low" &&
      input.classification.domain_sensitivity === "none" &&
      input.classification.vision_alignment === "high" &&
      input.classification.novelty === "routine" &&
      !duplicateLikely;
  }

  const meta: NodeMeta = {
    id,
    kind: input.kind,
    intent: input.intent,
    title: input.title.trim().slice(0, 40),
    state: autoEligible ? "approved" : "proposed",
    badge: autoEligible ? "auto" : "proposed",
    parent_id: input.parent_id ?? null,
    dependencies: input.dependencies ?? [],
    confidence: input.confidence,
    proposed_by: input.proposed_by ?? "drafter",
    priority: input.priority ?? "P2-later",
    cycle: input.cycle ?? null,
    outcome: input.kind === "Project" ? (input.outcome ?? null) : undefined,
    target_date: input.kind === "Milestone" ? (input.target_date ?? null) : undefined,
    layer: input.kind === "Project" ? (input.layer ?? null) : undefined,
    plane_kind: input.kind === "Plane" ? (input.plane_kind ?? null) : undefined,
    parent_plane_id:
      input.kind === "Plane" || input.kind === "Surface" ? (input.parent_plane_id ?? null) : undefined,
    manifest_globs: input.kind === "Surface" ? (input.manifest_globs ?? []) : undefined,
    surface_kind: input.kind === "Surface" ? (input.surface_kind ?? null) : undefined,
    surface_status: input.kind === "Surface" ? (input.surface_status ?? "proposed") : undefined,
    touches:
      input.kind === "Story" || input.kind === "Epic" || input.kind === "Task" || input.kind === "Subtask"
        ? (input.touches ?? [])
        : undefined,
    lock_id: input.kind === "Task" || input.kind === "Subtask" ? (input.lock_id ?? null) : undefined,
    priority_score:
      input.kind === "Task" || input.kind === "Subtask" ? (input.priority_score ?? null) : undefined,
    supersedes: input.kind === "Task" || input.kind === "Subtask" ? (input.supersedes ?? null) : undefined,
    classification: input.classification,
    placeholder: input.placeholder === true ? true : undefined,
    created_at: now,
    updated_at: now,
  };

  const dir = nodeDir(input.project, id);
  mkdirSync(dir, { recursive: true });
  mkdirSync(resolve(dir, "discussions"), { recursive: true });
  mkdirSync(resolve(dir, "outputs"), { recursive: true });
  writeFileSync(resolve(dir, "meta.json"), JSON.stringify(meta, null, 2));
  // Consultation kind has a different plan template — it's not a unit of work,
  // it's a meta-tracking surface for an off-platform conversation. The fields
  // are mirrored from meta.json (which is the canonical source of truth);
  // plan.md is just the human-readable representation. See drafter.md
  // "Consultation kind" section.
  const planMd = input.kind === "Consultation"
    ? `# Consultation: ${input.intent}\n\n## Intent\n${input.intent}\n\n## Expert role\n(to fill — e.g. "legal counsel", "tax accountant", "UX designer")\n\n## Channel\n(to fill — email / slack / calendly / phone / in-person)\n\n## Question\n(to fill — what you're asking the expert)\n\n## Answer (filled when conversation completes)\n(empty until the off-platform conversation completes; founder pastes their answer here)\n\n## Deadline\n(optional ISO date)\n`
    // Section order matches drafter.md → "Node emission discipline". The
    // 7th section `## Who benefits / What changes for them` was missing,
    // which let Drafter ship plans Allocator hand-backs on "who benefits
    // hand-wavy". Renaming `## Budget` → `## Budget (appetite)` matches
    // the principle's exact heading too.
    : `# Plan: ${input.intent}\n\n## Intent\n${input.intent}\n\n## Who benefits / What changes for them\n(to fill)\n\n## Non-goals\n(to fill)\n\n## Acceptance\n(to fill)\n\n## Dependencies\n${(input.dependencies ?? []).join(", ") || "(none)"}\n\n## Budget (appetite)\n(to fill)\n\n## Planned artifacts\n(to fill)\n`;
  writeFileSync(resolve(dir, "plan.md"), planMd);

  // Record parent-child edge in graph
  if (input.parent_id) {
    const g = readGraph(input.project);
    g.edges.push({ from: input.parent_id, to: id, kind: "parent-child" });
    for (const dep of input.dependencies ?? []) {
      g.edges.push({ from: dep, to: id, kind: "depends-on" });
    }
    writeGraph(input.project, g);
  }

  return meta;
}

export function proposePlan(project: string, nodeId: string, planMd: string): NodeMeta {
  const dir = nodeDir(project, nodeId);
  if (!existsSync(dir)) throw new Error(`node ${nodeId} not found`);
  writeFileSync(resolve(dir, "plan.md"), planMd);
  const meta = getNode(project, nodeId);
  meta.updated_at = new Date().toISOString();
  writeFileSync(resolve(dir, "meta.json"), JSON.stringify(meta, null, 2));
  return meta;
}

export function proposeEdge(project: string, edge: Edge): void {
  const g = readGraph(project);
  g.edges.push(edge);
  writeGraph(project, g);
}

export function listNodes(project: string): NodeMeta[] {
  ensureCanvas(project);
  const dir = nodesRoot(project);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((id) => existsSync(resolve(dir, id, "meta.json")))
    .map((id) => JSON.parse(readFileSync(resolve(dir, id, "meta.json"), "utf-8")) as NodeMeta);
}

export function getNode(project: string, id: string): NodeMeta {
  const metaPath = resolve(nodeDir(project, id), "meta.json");
  if (!existsSync(metaPath)) throw new Error(`node ${id} not found`);
  return JSON.parse(readFileSync(metaPath, "utf-8")) as NodeMeta;
}

export function getNodeFull(project: string, id: string): { meta: NodeMeta; plan: string } {
  const meta = getNode(project, id);
  const plan = readFileSync(resolve(nodeDir(project, id), "plan.md"), "utf-8");
  return { meta, plan };
}

export function getGraph(project: string): { nodes: NodeMeta[]; edges: Edge[] } {
  const nodes = listNodes(project);
  const g = readGraph(project);
  return { nodes, edges: g.edges };
}

// Convergence gate enforced at state transitions. Returns null if the transition is allowed,
// or a string explaining why it can't happen (founder-readable, used by HTTP route as 409 body).
function altitudeBlockReason(meta: NodeMeta, target: NodeState, allNodes: NodeMeta[]): string | null {
  if (target !== "approved") return null; // only the approved gate matters here
  if (meta.kind === "Story" || meta.kind === "Epic") {
    const touches = meta.touches ?? [];
    if (touches.length === 0) {
      return `${meta.kind} cannot reach state: approved with empty touches — Drafter must set the Surface(s) this work hits.`;
    }
    for (const sid of touches) {
      const surface = allNodes.find((n) => n.id === sid);
      if (!surface || surface.kind !== "Surface") {
        return `touched Surface ${sid} no longer exists — re-place this work.`;
      }
      if (surface.surface_status === "deprecated") {
        return `touched Surface "${surface.title}" is deprecated — re-place this work.`;
      }
      if (surface.surface_status === "proposed") {
        return `touched Surface "${surface.title}" is still proposed — founder must approve the Surface before Stories on it can be approved.`;
      }
    }
  }
  if (meta.kind === "Task" || meta.kind === "Subtask") {
    // Inherit from parent Story/Epic if Task itself doesn't carry touches.
    const inherited = (meta.touches ?? []).length > 0
      ? meta.touches!
      : (() => {
          const parent = meta.parent_id ? allNodes.find((n) => n.id === meta.parent_id) : null;
          return parent?.touches ?? [];
        })();
    if (inherited.length === 0) {
      return `${meta.kind} cannot reach state: approved without inherited touches — parent Story/Epic must declare its Surfaces first.`;
    }
  }
  return null;
}

export function updateState(project: string, id: string, state: NodeState, badge?: NodeBadge): NodeMeta {
  const meta = getNode(project, id);
  if (state !== meta.state) {
    const allNodes = listNodes(project);
    const blocked = altitudeBlockReason(meta, state, allNodes);
    if (blocked) throw new Error(blocked);
  }
  meta.state = state;
  if (badge) meta.badge = badge;
  meta.updated_at = new Date().toISOString();
  writeFileSync(resolve(nodeDir(project, id), "meta.json"), JSON.stringify(meta, null, 2));

  // A2.3: auto-rollup. When a Task/Subtask transitions to done, climb the
  // parent chain. Story/Epic ancestors auto-complete when every descendant
  // runnable node is done. Story/Epic themselves are not executable —
  // they exist as containers, and "done" means "all the work under me
  // shipped". Idempotent.
  if (state === "done") {
    rollupParentChain(project, meta.parent_id);
  }
  return meta;
}

const ROLLUP_KINDS = new Set(["Story", "Epic"]);
const RUNNABLE_KINDS = new Set(["Task", "Subtask"]);

function rollupParentChain(project: string, startParentId: string | null | undefined): void {
  const seen = new Set<string>();
  let cursor = startParentId ?? null;
  while (cursor && !seen.has(cursor)) {
    seen.add(cursor);
    let parent: NodeMeta;
    try { parent = getNode(project, cursor); } catch { return; }
    if (!ROLLUP_KINDS.has(parent.kind) || parent.state === "done") {
      cursor = parent.parent_id ?? null;
      continue;
    }
    // All runnable descendants must be done. Walk the subtree by parent_id.
    const all = listNodes(project);
    const byParent = new Map<string, NodeMeta[]>();
    for (const n of all) {
      if (!n.parent_id) continue;
      const list = byParent.get(n.parent_id) ?? [];
      list.push(n);
      byParent.set(n.parent_id, list);
    }
    let totalRunnable = 0;
    let doneRunnable = 0;
    let queue = [parent.id];
    while (queue.length > 0) {
      const cur = queue.shift()!;
      const kids = byParent.get(cur) ?? [];
      for (const k of kids) {
        if (RUNNABLE_KINDS.has(k.kind)) {
          totalRunnable++;
          if (k.state === "done") doneRunnable++;
        }
        queue.push(k.id);
      }
    }
    if (totalRunnable > 0 && totalRunnable === doneRunnable) {
      // Roll up this ancestor. Recursion happens via the next iteration of
      // the outer while loop — we move cursor to its parent after writing.
      parent.state = "done";
      parent.badge = "done";
      parent.updated_at = new Date().toISOString();
      writeFileSync(resolve(nodeDir(project, parent.id), "meta.json"), JSON.stringify(parent, null, 2));
    }
    cursor = parent.parent_id ?? null;
  }
}

export function updateNodeMeta(
  project: string,
  id: string,
  updates: Partial<
    Pick<
      NodeMeta,
      | "intent"
      | "title"
      | "state"
      | "badge"
      | "confidence"
      | "priority"
      | "cycle"
      | "outcome"
      | "target_date"
      | "layer"
      | "plane_kind"
      | "parent_plane_id"
      | "manifest_globs"
      | "surface_kind"
      | "surface_status"
      | "touches"
      | "lock_id"
      | "priority_score"
      | "supersedes"
      | "expert_role"
      | "channel"
      | "question"
      | "answer"
      | "deadline"
      | "answered_at"
    >
  > & { _cascade_summary?: string }
): NodeMeta {
  const meta = getNode(project, id);
  // Snapshot Surface-relevant fields so we can detect mutations that should cascade to touching nodes.
  const beforeManifest = JSON.stringify(meta.manifest_globs ?? []);
  const beforeStatus = meta.surface_status ?? null;
  const beforeTitle = meta.title;
  if (updates.intent !== undefined) meta.intent = updates.intent;
  if (updates.title !== undefined) meta.title = updates.title.trim().slice(0, 40);
  if (updates.state !== undefined) {
    if (updates.state !== meta.state) {
      const blocked = altitudeBlockReason(meta, updates.state, listNodes(project));
      if (blocked) throw new Error(blocked);
    }
    meta.state = updates.state;
  }
  if (updates.badge !== undefined) meta.badge = updates.badge;
  if (updates.confidence !== undefined) meta.confidence = updates.confidence;
  if (updates.priority !== undefined) meta.priority = updates.priority;
  if (updates.cycle !== undefined) meta.cycle = updates.cycle;
  if (updates.outcome !== undefined && meta.kind === "Project") meta.outcome = updates.outcome;
  if (updates.target_date !== undefined && meta.kind === "Milestone") meta.target_date = updates.target_date;
  if (updates.layer !== undefined && meta.kind === "Project") meta.layer = updates.layer;
  if (updates.plane_kind !== undefined && meta.kind === "Plane") meta.plane_kind = updates.plane_kind;
  if (updates.parent_plane_id !== undefined && (meta.kind === "Plane" || meta.kind === "Surface"))
    meta.parent_plane_id = updates.parent_plane_id;
  if (updates.manifest_globs !== undefined && meta.kind === "Surface") meta.manifest_globs = updates.manifest_globs;
  if (updates.surface_kind !== undefined && meta.kind === "Surface") meta.surface_kind = updates.surface_kind;
  if (updates.surface_status !== undefined && meta.kind === "Surface") meta.surface_status = updates.surface_status;
  if (updates.touches !== undefined && (meta.kind === "Story" || meta.kind === "Epic" || meta.kind === "Task" || meta.kind === "Subtask"))
    meta.touches = updates.touches;
  if (updates.lock_id !== undefined && (meta.kind === "Task" || meta.kind === "Subtask")) meta.lock_id = updates.lock_id;
  if (updates.priority_score !== undefined && (meta.kind === "Task" || meta.kind === "Subtask"))
    meta.priority_score = updates.priority_score;
  if (updates.supersedes !== undefined && (meta.kind === "Task" || meta.kind === "Subtask")) meta.supersedes = updates.supersedes;
  // Consultation fields (Session 4 — Pillar B). Only applied on Consultation
  // kind; the route handler is responsible for the answer-ripple side effects
  // (brain artifact write + comment + event). Setting `answered_at` here lets
  // the route preserve idempotency: a second PATCH with the same answer doesn't
  // re-fire the ripple.
  if (meta.kind === "Consultation") {
    if (updates.expert_role !== undefined) meta.expert_role = updates.expert_role;
    if (updates.channel !== undefined) meta.channel = updates.channel;
    if (updates.question !== undefined) meta.question = updates.question;
    if (updates.answer !== undefined) meta.answer = updates.answer;
    if (updates.deadline !== undefined) meta.deadline = updates.deadline;
    if (updates.answered_at !== undefined) meta.answered_at = updates.answered_at;
  }
  meta.updated_at = new Date().toISOString();
  writeFileSync(resolve(nodeDir(project, id), "meta.json"), JSON.stringify(meta, null, 2));

  // A2.3 auto-rollup: if this PATCH transitioned the node's state to "done",
  // climb the parent chain. Story/Epic ancestors auto-complete when every
  // descendant runnable node is done. Idempotent.
  if (updates.state === "done" && meta.state === "done") {
    rollupParentChain(project, meta.parent_id);
  }

  // Surface-edit cascade. If a Surface's manifest_globs / status / title changed, every node
  // touching this Surface gets a "surface-edited" badge and a one-line note. If the Surface
  // was retired, those nodes also transition to state: blocked.
  if (meta.kind === "Surface") {
    const manifestChanged = JSON.stringify(meta.manifest_globs ?? []) !== beforeManifest;
    const statusChanged = (meta.surface_status ?? null) !== beforeStatus;
    const renamed = meta.title !== beforeTitle;
    if (manifestChanged || statusChanged || renamed) {
      cascadeSurfaceEdit(project, meta, {
        manifestChanged,
        statusChanged,
        renamed,
        retired: statusChanged && meta.surface_status === "deprecated",
        cascadeSummary: updates._cascade_summary ?? buildDefaultCascadeSummary(meta, beforeTitle, beforeStatus, manifestChanged),
      });
    }
  }
  return meta;
}

function buildDefaultCascadeSummary(
  surface: NodeMeta,
  beforeTitle: string,
  beforeStatus: string | null,
  manifestChanged: boolean
): string {
  const parts: string[] = [];
  if (surface.title !== beforeTitle) parts.push(`renamed "${beforeTitle}" → "${surface.title}"`);
  if ((surface.surface_status ?? null) !== beforeStatus)
    parts.push(`status ${beforeStatus ?? "?"} → ${surface.surface_status ?? "?"}`);
  if (manifestChanged) parts.push(`manifest_globs updated`);
  return `Surface ${surface.id}: ${parts.join("; ") || "edited"}`;
}

function cascadeSurfaceEdit(
  project: string,
  surface: NodeMeta,
  flags: { manifestChanged: boolean; statusChanged: boolean; renamed: boolean; retired: boolean; cascadeSummary: string }
): void {
  const all = listNodes(project);
  const touchers = all.filter((n) => Array.isArray(n.touches) && n.touches.includes(surface.id));
  for (const t of touchers) {
    const next: NodeMeta = { ...t };
    next.badge = flags.retired ? "blocked" : ("drift" as NodeBadge);
    if (flags.retired && next.state !== "done" && next.state !== "abandoned") {
      next.state = "blocked";
    }
    next.updated_at = new Date().toISOString();
    writeFileSync(resolve(nodeDir(project, t.id), "meta.json"), JSON.stringify(next, null, 2));
    // Append a discussion entry capturing the cascade so the founder sees the reason inline.
    const dPath = resolve(nodeDir(project, t.id), "discussions", "surface-cascade.jsonl");
    const entry = JSON.stringify({
      ts: new Date().toISOString(),
      from: "system:canvas",
      kind: flags.retired ? "surface-retired" : flags.manifestChanged ? "surface-manifest-changed" : "surface-edited",
      surface_id: surface.id,
      surface_title: surface.title,
      summary: flags.cascadeSummary,
      action_required: flags.retired ? "re-place this work; node is now blocked" : "review impact",
    });
    try {
      mkdirSync(resolve(nodeDir(project, t.id), "discussions"), { recursive: true });
      const existing = existsSync(dPath) ? readFileSync(dPath, "utf-8") : "";
      writeFileSync(dPath, existing + entry + "\n");
    } catch {
      // discussion log is best-effort; meta.json is the canonical signal
    }
  }
}

export function deleteNode(project: string, id: string): { removedEdges: number; orphanedChildren: number } {
  ensureCanvas(project);
  const dir = nodeDir(project, id);
  if (!existsSync(dir)) throw new Error(`node not found: ${id}`);

  // Remove any edge referencing this node
  const g = readGraph(project);
  const before = g.edges.length;
  g.edges = g.edges.filter(e => e.from !== id && e.to !== id);
  writeGraph(project, g);
  const removedEdges = before - g.edges.length;

  // Count children pointed at this node so the caller can report them
  const children = listNodes(project).filter(n => n.parent_id === id);

  rmSync(dir, { recursive: true, force: true });

  return { removedEdges, orphanedChildren: children.length };
}

export function updateNodePlan(project: string, id: string, plan: string): NodeMeta {
  const dir = nodeDir(project, id);
  if (!existsSync(dir)) throw new Error(`node ${id} not found`);
  writeFileSync(resolve(dir, "plan.md"), plan);
  return updateNodeMeta(project, id, {});
}
